"""empty message

Revision ID: bdfef9fc8945
Revises: 48dee826a4ad
Create Date: 2023-10-31 21:41:47.481440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfef9fc8945'
down_revision = '48dee826a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accident', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
